name: CD - Deploy con Git Pull

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectarse al servidor y hacer git pull
        run: |
          ssh -o StrictHostKeyChecking=alumno@137.184.127.11"
            cd ~/lemp-sites/giuliano_blengino/practico-evaluativo-js &&
            git pull origin develop
          "
        env:
          # GitHub buscará este secreto para autenticarse vía SSH
          # El secreto debe contener la clave privada ya configurada
          # El servidor debe tener la clave pública en ~/.ssh/authorized_keys
          SSH_PRIVATE_KEY: ${{ ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICXd8piCwieh7AIWXPecOF7uj3GENeukHwslTbEhjcA9 g.blengino@itecriocuarto.org.ar }}
